# Generated by Django 6.0.7 on 2026-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
